name: pre-merge-checks
run-name: ${{ github.actor }} is checking your code consistency
on:
  pull_request:
    branches: [main, develop]
jobs:
  Lint-Check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run check
  React-Component-Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm test
